### ISSUE TITLE
Firefox support

### ISSUE THREAD

**Issue by phosph** [pablomatiasgomez/utn.ba-helper#51]
Muy buenas extensión, es bastante útil especialmente en el proceso de inscripción.

¿hay alguna intención de darle soporte a Firefox también? como usuario de firefox me encantaría poderla usar allí también sin tener que irme a chrome solo para usar el SIU Guarani.

**Comment by pablomatiasgomez** [comment]
Buenas! Hace mucho tiempo tuvo soporte para firefox pero realmente mantener dos plataformas es demasiado laburo... Diria que uses chrome cuando quieras usarla y listo jaja. Perdon!
